### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by BboyKeen** [kjdev/php-ext-hoedown#8]
Hey @kjdev 

Will this extension be PHP7 compatible ?

**Comment by kjdev** [comment]
PHP7 is not supported.

Will correspond.

**Comment by BboyKeen** [comment]
Do you know the amount of work to make it compatible ?

**Comment by kjdev** [comment]
PHP7 compatible development version.

https://github.com/kjdev/php-ext-hoedown/tree/php7
